"""RAIO X - 3

Revision ID: 0f63c42a2a96
Revises: 9243cff35786
Create Date: 2023-03-04 15:54:43.241259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f63c42a2a96'
down_revision = '9243cff35786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
