"""RAIO X - 2

Revision ID: 9243cff35786
Revises: f8420ee19382
Create Date: 2023-03-04 12:15:52.861113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9243cff35786'
down_revision = 'f8420ee19382'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home_team_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('away_team_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'team', ['home_team_id'], ['id'])
    op.create_foreign_key(None, 'game', 'team', ['winner_team_id'], ['id'])
    op.create_foreign_key(None, 'game', 'team', ['away_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'winner_team_id')
    op.drop_column('game', 'away_team_id')
    op.drop_column('game', 'home_team_id')
    # ### end Alembic commands ###
