"""RAIO X - 3

Revision ID: 956c393d220a
Revises: 0f63c42a2a96
Create Date: 2023-03-04 16:20:19.720256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956c393d220a'
down_revision = '0f63c42a2a96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
