"""RAIO X - 1

Revision ID: f8420ee19382
Revises: 5a78e686f36e
Create Date: 2023-03-04 12:06:13.668248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8420ee19382'
down_revision = '5a78e686f36e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_away_team_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_winner_team_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_home_team_id_fkey', 'game', type_='foreignkey')
    op.drop_column('game', 'away_team_id')
    op.drop_column('game', 'winner_team_id')
    op.drop_column('game', 'home_team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('winner_team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_home_team_id_fkey', 'game', 'team', ['home_team_id'], ['id'])
    op.create_foreign_key('game_winner_team_id_fkey', 'game', 'team', ['winner_team_id'], ['id'])
    op.create_foreign_key('game_away_team_id_fkey', 'game', 'team', ['away_team_id'], ['id'])
    # ### end Alembic commands ###
